import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        main: {
          DEFAULT: "var(--color-main)",
          hovered: "var(--color-main-hovered)",
          container: "var(--color-main-container)",
          "container-hovered": "var(--color-main-container-hovered)",
          variant: "var(--color-main-variant)",
        },
        ai: {
          DEFAULT: "var(--color-ai)",
        },
        "on-ai": "var(--color-on-ai)",
        "on-main": "var(--color-on-main)",
        "on-main-container": "var(--color-on-main-container)",
        "on-main-variant": "var(--color-on-main-variant)",
        support: {
          DEFAULT: "var(--color-support)",
          hovered: "var(--color-support-hovered)",
          container: "var(--color-support-container)",
          "container-hovered": "var(--color-support-container-hovered)",
          variant: "var(--color-support-variant)",
        },
        "on-support": "var(--color-on-support)",
        "on-support-container": "var(--color-on-support-container)",
        accent: {
          DEFAULT: "var(--color-accent)",
          hovered: "var(--color-accent-hovered)",
          container: "var(--color-accent-container)",
          "container-hovered": "var(--color-accent-container-hovered)",
          variant: "var(--color-accent-variant)",
        },
        "on-accent": "var(--color-on-accent)",
        "on-accent-container": "var(--color-on-accent-container)",
        success: {
          DEFAULT: "var(--color-success)",
          hovered: "var(--color-success-hovered)",
          container: "var(--color-success-container)",
          "container-hovered": "var(--color-success-container-hovered)",
        },
        "on-success": "var(--color-on-success)",
        "on-success-container": "var(--color-on-success-container)",
        alert: {
          DEFAULT: "var(--color-alert)",
          hovered: "var(--color-alert-hovered)",
          container: "var(--color-alert-container)",
          "container-hovered": "var(--color-alert-container-hovered)",
        },
        "on-alert": "var(--color-on-alert)",
        "on-alert-container": "var(--color-on-alert-container)",
        error: {
          DEFAULT: "var(--color-error)",
          hovered: "var(--color-error-hovered)",
          container: "var(--color-error-container)",
          "container-hovered": "var(--color-error-container-hovered)",
        },
        "on-error": "var(--color-on-error)",
        "on-error-container": "var(--color-on-error-container)",
        info: {
          DEFAULT: "var(--color-info)",
          hovered: "var(--color-info-hovered)",
          container: "var(--color-info-container)",
          "container-hovered": "var(--color-info-container-hovered)",
        },
        "on-info": "var(--color-on-info)",
        "on-info-container": "var(--color-on-info-container)",
        neutral: {
          DEFAULT: "var(--color-neutral)",
          hovered: "var(--color-neutral-hovered)",
          container: "var(--color-neutral-container)",
          "container-hovered": "var(--color-neutral-container-hovered)",
        },
        "on-neutral": "var(--color-on-neutral)",
        "on-neutral-container": "var(--color-on-neutral-container)",
        background: {
          DEFAULT: "var(--color-background)",
          variant: "var(--color-background-variant)",
        },
        "on-background": "var(--color-on-background)",
        "on-background-variant": "var(--color-on-background-variant)",
        surface: {
          DEFAULT: "var(--color-surface)",
          hovered: "var(--color-surface-hovered)",
          inverse: "var(--color-surface-inverse)",
          "inverse-hovered": "var(--color-surface-inverse-hovered)",
          dark: "var(--color-surface-dark)",
          "dark-hovered": "var(--color-surface-dark-hovered)",
        },
        "on-surface": "var(--color-on-surface)",
        "on-surface-inverse": "var(--color-on-surface-inverse)",
        "on-surface-dark": "var(--color-on-surface-dark)",
        outline: {
          DEFAULT: "var(--color-outline)",
          high: "var(--color-outline-high)",
        },
        overlay: "var(--color-overlay)",
        "on-overlay": "var(--color-on-overlay)",
        shadow: "var(--color-shadow)",
        focus: "var(--color-focus)",
      },
      spacing: {
        none: "var(--spacing-none)",
        sm: "var(--spacing-sm)",
        md: "var(--spacing-md)",
        lg: "var(--spacing-lg)",
        xl: "var(--spacing-xl)",
        "2xl": "var(--spacing-2xl)",
        "3xl": "var(--spacing-3xl)",
      },
      borderRadius: {
        none: "var(--radius-none)",
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        full: "var(--radius-full)",
      },
      borderWidth: {
        none: "var(--border-none)",
        sm: "var(--border-sm)",
        md: "var(--border-md)",
        lg: "var(--border-lg)",
      },
      transitionDuration: {
        short: "var(--duration-short)",
        medium: "var(--duration-medium)",
        long: "var(--duration-long)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        decelerate: "var(--ease-decelerate)",
        accelerate: "var(--ease-accelerate)",
        "standard-back": "var(--ease-standard-back)",
        "decelerate-back": "var(--ease-decelerate-back)",
        "accelerate-back": "var(--ease-accelerate-back)",
      },
      fontFamily: {
        sans: ["var(--font-family)"],
      },
    },
  },
  plugins: [],
};
export default config;
